graph TD
    A[Step 1: Define Objectives<br> -Business Impact Analysis] --> B[Step 2: Define Technical Scope<br> System Architecture, Tech Stack ]
    B --> C[Step 3: Application Decomposition<br> Data Flow Diagrams, Assets, Actors]
    C --> D[Step 4: Threat Analysis<br> Use STRIDE, Identify Threats]
    D --> E[Step 5: Vulnerability Analysis<br> Find Weaknesses and Gaps]
    E --> F[Step 6: Attack Simulation<br> Simulate Possible Attacks]
    F --> G[Step 7: Risk & Impact Analysis<br>Prioritize Based on Risk]

    style A fill:#cfe2ff,stroke:#6fa8dc,stroke-width:2px,color:#003366
    style B fill:#d9ead3,stroke:#38761d,stroke-width:2px,color:#274e13
    style C fill:#fff2cc,stroke:#b45f06,stroke-width:2px,color:#7f6000
    style D fill:#fce5cd,stroke:#cc4125,stroke-width:2px,color:#990000
    style E fill:#f4cccc,stroke:#a61c00,stroke-width:2px,color:#660000
    style F fill:#d9d2e9,stroke:#674ea7,stroke-width:2px,color:#351c75
    style G fill:#d0e0e3,stroke:#134f5c,stroke-width:2px,color:#0c343d
